name: Docker Image CI

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Export release code
        if: (success() || failure())
        id: releasecode #version number in a more comprehensible format: 0.1.YearMonthDay in UTC
        run: |
          export VERSION=$(grep APP_VERSION= .env | cut -d '=' -f2)
          export RELEASE=$VERSION.$(date --utc +%y%m%d)
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "releasename=$RELEASE" >> $GITHUB_OUTPUT
      - name: Setting APP_NAME
        run: |
          export NAME=$(grep APP_NAME= .env | cut -d '=' -f2)
          echo "APP_NAME=$NAME" >> $GITHUB_ENV
      - name: Print app name
        run: echo "APP_NAME = $APP_NAME"

      - name: Setting APP_ENV for main
        if: contains( github.ref, 'main' ) || contains( github.base_ref, 'main' )
        run: |
          echo "APP_ENV=latest" >> $GITHUB_ENV
          echo "APP_BUILD=latest" >> $GITHUB_ENV
      - name: Setting APP_ENV for development
        if: contains( github.ref, 'development' ) || contains( github.base_ref, 'development' )
        run: |
          echo "APP_ENV=development" >> $GITHUB_ENV
          echo "APP_BUILD=development-${RELEASE}" >> $GITHUB_ENV

      - name: Print definitive APP_ENV
        run: echo "APP_ENV is now $APP_ENV and APP_BUILD is now $APP_BUILD"
      - name: Build the Docker image
        run: docker compose build --build-arg APP_ENV=$APP_ENV --build-arg APP_BUILD=$APP_BUILD --build-arg APP_BUILD_ALL_FIXTURES=true
      - name: Run the docker image
        run: docker compose up -d
      - name: Taking some sleep (for containers to come up)
        run: sleep 20
      - name: Check if all containers are running
        run: docker ps
      - name: Dumping the logs
        run: docker compose logs
      - name: Show all images
        run: docker images
      - name: Login to Container Registry
        id: containerregistry-login
        run: |
         if [ "${{ secrets.GITHUB_TOKEN }}" != "" ]; then
           echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $(cut -d'/' -f1 <<< $GITHUB_REPOSITORY) --password-stdin
           echo "success=true" >> $GITHUB_OUTPUT
         else
           echo "success=false" >> $GITHUB_OUTPUT
         fi

      - if: steps.containerregistry-login.outputs.success == 'true' && github.ref == 'refs/heads/main'
        name: Push to Container Registry (main → latest)
        run: docker compose push
      - if: steps.containerregistry-login.outputs.success == 'true' && github.ref == 'refs/heads/development'
        name: Push to Container Registry (development → development-{release})
        run: docker compose push

      - name: Print release name
        if: (success() || failure())
        run: echo $RELEASENAME
        env:
          RELEASENAME: ${{ steps.releasecode.outputs.releasename }}
      - name: Create Release
        if: github.ref == 'refs/heads/main' && ( success() || failure() )
        id: create_release
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.releasecode.outputs.releasename }}
          name: ${{ steps.releasecode.outputs.releasename }}
          draft: false
          prerelease: false
      - name: Create Pre-Release (development)
        if: github.ref == 'refs/heads/development' && ( success() || failure() )
        id: create_prerelease
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.releasecode.outputs.releasename }}-development
          release_name: ${{ steps.releasecode.outputs.releasename }}-development
          draft: false
          prerelease: true
      - name: Chores
        if: (success() || failure())
        run: docker compose down
