# Generates SVG files from UML files (for documentation purposes)
name: generate plantuml
on: push
# The plantuml action commits the rendered SVG files back to the repository.
permissions:
  contents: write
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: checkout
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
        with:
          fetch-depth: 1
      - name: plantuml
        id: plantuml
        uses: grassedge/generate-plantuml-action@4936762686b831393728392054322cfde20645e8 # v1.5
        with:
          message: "Render PlantUML files"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}